import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:unicons/unicons.dart';

class ModelCategoryMenu {
  Map<String, List<Map<String, dynamic>>> groupedCategoryItemsID = {
    'Tagihan': [
      {'icon': UniconsLine.phone, 'label': 'Pulsa'},
      {'icon': Icons.electric_bolt, 'label': 'Listrik'},
      {'icon': UniconsLine.money_insert, 'label': 'Uang Elektronik'},
      {'icon': Icons.data_object, 'label': 'Paket Data'},
      {'icon': Icons.water, 'label': 'Air PDAM'},
      {'icon': UniconsLine.globe, 'label': 'Internet & TV'},
      {'icon': Icons.cable, 'label': 'Cable'},
      {'icon': UniconsLine.card_atm, 'label': 'Kartu Kredit'},
      {'icon': UniconsLine.clock, 'label': 'Pascabayar'},
    ],
    'Konsultasi': [
      {'icon': UniconsLine.building, 'label': 'Kontraktor'},
      {'icon': UniconsLine.paint_tool, 'label': 'Design Interior'},
      {'icon': UniconsLine.heart, 'label': 'WO'},
      {'icon': UniconsLine.bookmark, 'label': 'EO'},
      {'icon': Icons.production_quantity_limits, 'label': 'Design Produk'},
      {'icon': UniconsLine.airplay, 'label': 'Design Grafis'},
      {'icon': UniconsLine.dollar_sign, 'label': 'Pajak'},
      {'icon': Icons.calculate, 'label': 'Financial'},
      {'icon': UniconsLine.bill, 'label': 'Notaris'},
      {'icon': UniconsLine.heart_medical, 'label': 'Asuransi'},
      {'icon': Icons.handyman, 'label': 'Property'},
      {'icon': Icons.man_3, 'label': 'Pengacara'},
      {'icon': Icons.branding_watermark, 'label': 'Advertising'},
      {'icon': Icons.backpack, 'label': 'Fashion'},
      {'icon': UniconsLine.music, 'label': 'Guru Musik'},
      {'icon': UniconsLine.language, 'label': 'Guru Bahasa'},
      {'icon': Icons.abc, 'label': 'Guru Mata Pelajaran'},
      {'icon': Icons.speaker, 'label': 'Guru Dance'},
      {'icon': Icons.man_2, 'label': 'Private tutor'},
      {'icon': Icons.school, 'label': 'Home Schooling'},
      {'icon': UniconsLine.paint_tool, 'label': 'Design'},
    ],
    'Bisnis': [
      {'icon': FontAwesomeIcons.userTag, 'label': 'Branding'},
      {'icon': UniconsLine.sign_alt, 'label': 'Billiboard/Signage'},
      {'icon': UniconsLine.globe, 'label': 'SEO'},
      {'icon': UniconsLine.web_grid, 'label': 'Digital Marketing'},
      {'icon': Icons.tv, 'label': 'TV'},
      {'icon': Icons.newspaper, 'label': 'Magazine'},
      {'icon': Icons.radio, 'label': 'Radio'},
      {'icon': Icons.girl, 'label': 'SPG'},
      {'icon': UniconsLine.youtube, 'label': 'Influencer'},
      {'icon': Icons.home, 'label': 'Production House'},
      {'icon': Icons.support_agent, 'label': 'Creative Agency'},
      {'icon': UniconsLine.monitor, 'label': 'Performance'},
      {'icon': UniconsLine.folder_network, 'label': 'Marketing'},
    ],
    'Kesehatan': [
      {'icon': FontAwesomeIcons.syringe, 'label': 'Infus Vitamin'},
      {'icon': FontAwesomeIcons.userDoctor, 'label': 'Dr umum Panggilan'},
      {
        'icon': UniconsLine.hospital,
        'label': 'Menemanin /Konsultasi Check up luar negeri'
      },
      {'icon': FontAwesomeIcons.wheelchair, 'label': 'Helper disabilitas'},
      {'icon': FontAwesomeIcons.syringe, 'label': 'Vaksin'},
      {'icon': FontAwesomeIcons.syringe, 'label': 'Suntik'},
      {'icon': Icons.bedroom_baby, 'label': 'Pengasuh Pasca kelahiran'},
    ],
    'kecantikan': [
      {'icon': FontAwesomeIcons.scissors, 'label': 'Hair Style'},
      {'icon': Icons.medical_information, 'label': 'Make up'},
      {'icon': FontAwesomeIcons.hand, 'label': 'Waxing'},
      {'icon': FontAwesomeIcons.brush, 'label': 'Makeup Artist'},
      {'icon': FontAwesomeIcons.handScissors, 'label': 'Nail art'},
      {'icon': UniconsLine.eye, 'label': 'Bulu mata'},
      {'icon': FontAwesomeIcons.scissors, 'label': 'Hair do'},
    ],
    'Donasi': [
      {'icon': FontAwesomeIcons.cow, 'label': 'Qurban'},
      {'icon': FontAwesomeIcons.donate, 'label': 'Donasi'},
      {'icon': FontAwesomeIcons.quran, 'label': 'Zakat'},
      {'icon': FontAwesomeIcons.mosque, 'label': 'Wakaf'},
      {'icon': FontAwesomeIcons.mosque, 'label': 'Fidyah'},
    ],
    'Reservasi': [
      {'icon': Icons.restaurant, 'label': 'Restaurant'},
      {'icon': Icons.coffee, 'label': 'Cafe'},
      {'icon': Icons.coffee_maker, 'label': 'Coffee Shop'},
      {'icon': UniconsLine.coffee, 'label': 'Kopitiam'},
      {'icon': UniconsLine.record_audio, 'label': 'Studio'},
      {'icon': Icons.meeting_room, 'label': 'Ballroom'},
      {'icon': Icons.spa, 'label': 'Spa'},
      {'icon': Icons.spa, 'label': 'Massage'},
      {'icon': UniconsLine.hospital, 'label': 'Klinik'},
      {'icon': UniconsLine.hospital, 'label': 'Rumah Sakit'},
      {'icon': UniconsLine.home_alt, 'label': 'Skin Care'},
      {'icon': FontAwesomeIcons.tooth, 'label': 'Dental'},
    ],
    'Profesional': [
      {'icon': FontAwesomeIcons.paintbrush, 'label': 'Pelukis'},
      {'icon': FontAwesomeIcons.language, 'label': 'Translator'},
      {'icon': FontAwesomeIcons.suitcase, 'label': 'Biro Jasa'},
      {'icon': Icons.restaurant, 'label': 'Private Chef'},
      {'icon': Icons.security, 'label': 'Bodyguard'},
      {'icon': Icons.camera, 'label': 'Photographer'},
      {'icon': Icons.video_camera_back, 'label': 'Videographer'},
      {'icon': Icons.design_services, 'label': 'Design'},
      {'icon': Icons.chair, 'label': 'Decoration'},
    ],
    'TenagaKerja': [
      {'icon': FontAwesomeIcons.hammer, 'label': 'Tenaga kerja /infal'},
      {'icon': Icons.girl, 'label': 'ART'},
      {'icon': Icons.security, 'label': 'Security'},
      {'icon': Icons.drive_eta, 'label': 'Sopir'},
      {'icon': Icons.cleaning_services, 'label': 'Cleaning Service'},
      {'icon': FontAwesomeIcons.codeFork, 'label': 'Tukang Kebun'},
    ],
    'Hewan Peliharan': [
      {'icon': FontAwesomeIcons.broom, 'label': 'Breeder Hewan'},
      {'icon': Icons.cabin, 'label': 'Pengiriman Hewan'},
      {'icon': Icons.wash, 'label': 'Pet Grooming'},
      {'icon': Icons.pets, 'label': 'Penitipan Hewan'},
      {'icon': Icons.pets, 'label': 'Jual Beli Hewan'},
    ],
    'Layanan Pemerintah': [
      {'icon': Icons.school, 'label': 'Daftar BP Jamsostek'},
      {'icon': FontAwesomeIcons.moneyBill, 'label': 'Pajak PBB'},
      {'icon': FontAwesomeIcons.moneyBill, 'label': 'Daerah Pajak'},
      {'icon': FontAwesomeIcons.idCardClip, 'label': 'E-Samsat'},
      {'icon': FontAwesomeIcons.idCard, 'label': 'Signal'},
      {'icon': FontAwesomeIcons.moneyCheckDollar, 'label': 'SPT Bulanan'},
      {'icon': FontAwesomeIcons.moneyCheckDollar, 'label': 'Retribusi'},
      {'icon': FontAwesomeIcons.passport, 'label': 'Paspor'},
      {'icon': FontAwesomeIcons.simCard, 'label': 'E-Tilang'},
      {'icon': FontAwesomeIcons.bridge, 'label': 'Bayar KUA'},
      {'icon': FontAwesomeIcons.certificate, 'label': 'SBN'},
      {'icon': Icons.flag, 'label': 'Penerimaan Negara'},
    ],
    'Event Organizer': [
      {'icon': FontAwesomeIcons.drum, 'label': 'Band'},
      {'icon': FontAwesomeIcons.microphone, 'label': 'Penyanyi'},
      {'icon': FontAwesomeIcons.guitar, 'label': 'Musisi'},
      {'icon': FontAwesomeIcons.masksTheater, 'label': 'Badut'},
      {'icon': FontAwesomeIcons.wandMagicSparkles, 'label': 'Pesulap'},
      {'icon': Icons.headset_mic, 'label': 'MC'},
    ],
    'Home Service': [
      {'icon': Icons.water_drop, 'label': 'Air Mampet'},
      {'icon': FontAwesomeIcons.mosquito, 'label': 'Semprot nyamuk'},
      {'icon': Icons.man, 'label': 'Dust Buster'},
      {'icon': Icons.cleaning_services, 'label': 'Cleaning'},
      {'icon': Icons.dry_cleaning, 'label': 'Laudry'},
      {'icon': Icons.fastfood, 'label': 'Catering'},
      {'icon': Icons.electric_bolt, 'label': 'Mekanik Listrik'},
      {'icon': Icons.handyman, 'label': 'Tukang'},
      {'icon': Icons.shopping_bag, 'label': 'Shop and Drive'},
      {'icon': UniconsLine.car_wash, 'label': 'Steam Mobile'},
      {'icon': UniconsLine.box, 'label': 'Pindahan'},
      {'icon': FontAwesomeIcons.fan, 'label': 'Ac Cleaning'},
    ],
    'Exprience': [
      {'icon': Icons.water, 'label': 'Water Sport'},
      {'icon': Icons.motorcycle, 'label': 'Can am'},
      {'icon': FontAwesomeIcons.skating, 'label': 'Jetski'},
      {'icon': FontAwesomeIcons.broomBall, 'label': 'Billiard'},
      {'icon': FontAwesomeIcons.fish, 'label': 'Fishing'},
      {'icon': FontAwesomeIcons.helicopter, 'label': 'Helicopter'},
      {'icon': FontAwesomeIcons.ship, 'label': 'Pinisi'},
      {'icon': FontAwesomeIcons.plane, 'label': 'Private Jet'},
      {'icon': FontAwesomeIcons.planeUp, 'label': 'Pesawat Charter'},
    ],
    'Lain-Lain': [
      {'icon': Icons.shopping_bag, 'label': 'Jastip'},
      {'icon': Icons.fire_truck, 'label': 'Alat Berat'},
      {'icon': Icons.home, 'label': 'Cicil/ Sewa Properti'},
      {'icon': Icons.currency_exchange, 'label': 'Investasi Mas / Reksadana'},
    ],
  };

  Map<String, List<Map<String, dynamic>>> groupedCategoryItemsEN = {
    'Bill': [
      {'icon': UniconsLine.phone, 'label': 'Mobile Credit'},
      {'icon': Icons.electric_bolt, 'label': 'Electricity'},
      {'icon': UniconsLine.money_insert, 'label': 'Electronic Money'},
      {'icon': Icons.data_object, 'label': 'Data Package'},
      {'icon': Icons.water, 'label': 'Tap Water'},
      {'icon': UniconsLine.globe, 'label': 'Internet & TV'},
      {'icon': Icons.cable, 'label': 'Cable'},
      {'icon': UniconsLine.card_atm, 'label': 'Credit Card'},
      {'icon': UniconsLine.clock, 'label': 'Postpaid'},
    ],
    'Consultation': [
      {'icon': UniconsLine.building, 'label': 'Contractor'},
      {'icon': UniconsLine.paint_tool, 'label': 'Interior Design'},
      {'icon': UniconsLine.heart, 'label': 'Wedding Organizer (WO)'},
      {'icon': UniconsLine.bookmark, 'label': 'Event Organizer (EO)'},
      {'icon': Icons.production_quantity_limits, 'label': 'Product Design'},
      {'icon': UniconsLine.airplay, 'label': 'Graphic Design'},
      {'icon': UniconsLine.dollar_sign, 'label': 'Tax'},
      {'icon': Icons.calculate, 'label': 'Financial'},
      {'icon': UniconsLine.bill, 'label': 'Notary'},
      {'icon': UniconsLine.heart_medical, 'label': 'Insurance'},
      {'icon': Icons.handyman, 'label': 'Property'},
      {'icon': Icons.man_3, 'label': 'Lawyer'},
      {'icon': Icons.branding_watermark, 'label': 'Advertising'},
      {'icon': Icons.backpack, 'label': 'Fashion'},
      {'icon': UniconsLine.music, 'label': 'Music Teacher'},
      {'icon': UniconsLine.language, 'label': 'Language Teacher'},
      {'icon': Icons.abc, 'label': 'Subject Teacher'},
      {'icon': Icons.speaker, 'label': 'Dance Teacher'},
      {'icon': Icons.man_2, 'label': 'Private Tutor'},
      {'icon': Icons.school, 'label': 'Home Schooling'},
      {'icon': UniconsLine.paint_tool, 'label': 'Design'},
    ],
    'Business': [
      {'icon': FontAwesomeIcons.userTag, 'label': 'Branding'},
      {'icon': UniconsLine.sign_alt, 'label': 'Billboard/Signage'},
      {'icon': UniconsLine.globe, 'label': 'SEO'},
      {'icon': UniconsLine.web_grid, 'label': 'Digital Marketing'},
      {'icon': Icons.tv, 'label': 'TV'},
      {'icon': Icons.newspaper, 'label': 'Magazine'},
      {'icon': Icons.radio, 'label': 'Radio'},
      {'icon': Icons.girl, 'label': 'SPG'},
      {'icon': UniconsLine.youtube, 'label': 'Influencer'},
      {'icon': Icons.home, 'label': 'Production House'},
      {'icon': Icons.support_agent, 'label': 'Creative Agency'},
      {'icon': UniconsLine.monitor, 'label': 'Performance'},
      {'icon': UniconsLine.folder_network, 'label': 'Marketing'},
    ],
    'Health': [
      {'icon': FontAwesomeIcons.syringe, 'label': 'Vitamin Infusion'},
      {
        'icon': FontAwesomeIcons.userDoctor,
        'label': 'General Practitioner on Call'
      },
      {
        'icon': UniconsLine.hospital,
        'label': 'Accompanying/Consultation for International Check-up'
      },
      {'icon': FontAwesomeIcons.wheelchair, 'label': 'Disability Helper'},
      {'icon': FontAwesomeIcons.syringe, 'label': 'Vaccination'},
      {'icon': FontAwesomeIcons.syringe, 'label': 'Injection'},
      {'icon': Icons.bedroom_baby, 'label': 'Postpartum Caregiver'},
    ],
    'Beauty': [
      {'icon': FontAwesomeIcons.scissors, 'label': 'Hair Style'},
      {'icon': Icons.medical_information, 'label': 'Makeup'},
      {'icon': FontAwesomeIcons.hand, 'label': 'Waxing'},
      {'icon': FontAwesomeIcons.brush, 'label': 'Makeup Artist'},
      {'icon': FontAwesomeIcons.handScissors, 'label': 'Nail Art'},
      {'icon': UniconsLine.eye, 'label': 'Eyelashes'},
      {'icon': FontAwesomeIcons.scissors, 'label': 'Hairdo'},
    ],
    'Donation': [
      {'icon': FontAwesomeIcons.cow, 'label': 'Sacrifice'},
      {'icon': FontAwesomeIcons.donate, 'label': 'Donation'},
      {'icon': FontAwesomeIcons.quran, 'label': 'Alms (Zakat)'},
      {'icon': FontAwesomeIcons.mosque, 'label': 'Endowment (Wakaf)'},
      {'icon': FontAwesomeIcons.mosque, 'label': 'Fidya (Fidyah)'},
    ],
    'Reservation': [
      {'icon': Icons.restaurant, 'label': 'Restaurant'},
      {'icon': Icons.coffee, 'label': 'Cafe'},
      {'icon': Icons.coffee_maker, 'label': 'Coffee Shop'},
      {'icon': UniconsLine.coffee, 'label': 'Kopitiam'},
      {'icon': UniconsLine.record_audio, 'label': 'Studio'},
      {'icon': Icons.meeting_room, 'label': 'Ballroom'},
      {'icon': Icons.spa, 'label': 'Spa'},
      {'icon': Icons.spa, 'label': 'Massage'},
      {'icon': UniconsLine.hospital, 'label': 'Clinic'},
      {'icon': UniconsLine.hospital, 'label': 'Hospital'},
      {'icon': UniconsLine.home_alt, 'label': 'Skin Care'},
      {'icon': FontAwesomeIcons.tooth, 'label': 'Dental'},
    ],
    'Professional': [
      {'icon': FontAwesomeIcons.paintbrush, 'label': 'Painter'},
      {'icon': FontAwesomeIcons.language, 'label': 'Translator'},
      {'icon': FontAwesomeIcons.suitcase, 'label': 'Service Bureau'},
      {'icon': Icons.restaurant, 'label': 'Private Chef'},
      {'icon': Icons.security, 'label': 'Bodyguard'},
      {'icon': Icons.camera, 'label': 'Photographer'},
      {'icon': Icons.video_camera_back, 'label': 'Videographer'},
      {'icon': Icons.design_services, 'label': 'Design'},
      {'icon': Icons.chair, 'label': 'Decoration'},
    ],
    'Labor': [
      {'icon': FontAwesomeIcons.hammer, 'label': 'Labor / Casual Worker'},
      {'icon': Icons.girl, 'label': 'Housemaid'},
      {'icon': Icons.security, 'label': 'Security'},
      {'icon': Icons.drive_eta, 'label': 'Driver'},
      {'icon': Icons.cleaning_services, 'label': 'Cleaning Service'},
      {'icon': FontAwesomeIcons.codeFork, 'label': 'Gardener'},
    ],
    'Pet Services': [
      {'icon': FontAwesomeIcons.broom, 'label': 'Animal Breeder'},
      {'icon': Icons.cabin, 'label': 'Pet Shipping'},
      {'icon': Icons.wash, 'label': 'Pet Grooming'},
      {'icon': Icons.pets, 'label': 'Pet Boarding'},
      {'icon': Icons.pets, 'label': 'Pet Trading'},
    ],
    'Government Services': [
      {'icon': Icons.school, 'label': 'BP Jamsostek Registration'},
      {'icon': FontAwesomeIcons.moneyBill, 'label': 'Property Tax (PBB)'},
      {'icon': FontAwesomeIcons.moneyBill, 'label': 'Local Taxes'},
      {
        'icon': FontAwesomeIcons.idCardClip,
        'label': 'E-Samsat (Online Vehicle Tax Payment)'
      },
      {
        'icon': FontAwesomeIcons.idCard,
        'label': 'Signal (Vehicle Registration)'
      },
      {
        'icon': FontAwesomeIcons.moneyCheckDollar,
        'label': 'Monthly Tax Return (SPT Bulanan)'
      },
      {'icon': FontAwesomeIcons.moneyCheckDollar, 'label': 'Retribution'},
      {'icon': FontAwesomeIcons.passport, 'label': 'Passport'},
      {
        'icon': FontAwesomeIcons.simCard,
        'label': 'E-Tilang (Electronic Traffic Ticket)'
      },
      {
        'icon': FontAwesomeIcons.bridge,
        'label': 'Religious Affairs Office Payment (KUA)'
      },
      {'icon': FontAwesomeIcons.certificate, 'label': 'Government Bonds (SBN)'},
      {'icon': Icons.flag, 'label': 'State Revenue'},
    ],
    'Event Organizer': [
      {'icon': FontAwesomeIcons.drum, 'label': 'Band'},
      {'icon': FontAwesomeIcons.microphone, 'label': 'Singer'},
      {'icon': FontAwesomeIcons.guitar, 'label': 'Musician'},
      {'icon': FontAwesomeIcons.masksTheater, 'label': 'Clown'},
      {'icon': FontAwesomeIcons.wandMagicSparkles, 'label': 'Magician'},
      {'icon': Icons.headset_mic, 'label': 'MC (Master of Ceremony)'},
    ],
    'Home Service': [
      {'icon': Icons.water_drop, 'label': 'Clogged Water'},
      {'icon': FontAwesomeIcons.mosquito, 'label': 'Mosquito Repellent'},
      {'icon': Icons.man, 'label': 'Dust Buster'},
      {'icon': Icons.cleaning_services, 'label': 'Cleaning'},
      {'icon': Icons.dry_cleaning, 'label': 'Laundry'},
      {'icon': Icons.fastfood, 'label': 'Catering'},
      {'icon': Icons.electric_bolt, 'label': 'Electrical Mechanic'},
      {'icon': Icons.handyman, 'label': 'Handyman'},
      {'icon': Icons.shopping_bag, 'label': 'Shop and Drive'},
      {'icon': UniconsLine.car_wash, 'label': 'Mobile Steam'},
      {'icon': UniconsLine.box, 'label': 'Moving'},
      {'icon': FontAwesomeIcons.fan, 'label': 'AC Cleaning'},
    ],
    'Experience': [
      {'icon': Icons.water, 'label': 'Water Sport'},
      {'icon': Icons.motorcycle, 'label': 'Can-Am'},
      {'icon': FontAwesomeIcons.skating, 'label': 'Jet Ski'},
      {'icon': FontAwesomeIcons.broomBall, 'label': 'Billiards'},
      {'icon': FontAwesomeIcons.fish, 'label': 'Fishing'},
      {'icon': FontAwesomeIcons.helicopter, 'label': 'Helicopter'},
      {'icon': FontAwesomeIcons.ship, 'label': 'Pinisi'},
      {'icon': FontAwesomeIcons.plane, 'label': 'Private Jet'},
      {'icon': FontAwesomeIcons.planeUp, 'label': 'Charter Plane'},
    ],
    'Others': [
      {'icon': Icons.shopping_bag, 'label': 'Personal Shopper'},
      {'icon': Icons.fire_truck, 'label': 'Heavy Equipment'},
      {'icon': Icons.home, 'label': 'Installment/ Rental Property'},
      {
        'icon': Icons.currency_exchange,
        'label': 'Gold Investment / Mutual Funds'
      },
    ],
  };
}
